model:
  base_learning_rate: 6e-05
  target: mldm.models.mtldm.MedicalTranslationLDM
  params:
    linear_start: 0.0015
    linear_end: 0.0125
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "target"
    cond_stage_key: "txt"
    semantic_key: "source"
    edge_key: "edge"
    label_key: "label"
    semantic_beta: 0.95
    image_size: 64
    channels: 4
    cond_stage_trainable: False
    conditioning_key: crossattn
    scale_factor: 0.1408
    monitor: 'val/loss_simple_ema'

    unet_config:
      target: mldm.modules.diffusionmodules.dsmodel.DomainSpecialUNetModel
      params:
        image_size: 64
        in_channels: 8
        out_channels: 4
        num_domains: 3      # Task domains
        hint_channels: 4
        model_channels: 128
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4, 2]  # 64, 32, 16, 8, 4
        num_head_channels: 64
        use_spatial_transformer: true
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ckpt_path: "/home/first/code/MTDiff/checkpoint/autoencode_kl_8.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 512
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
            - 1
            - 2
            - 4
            - 4
          num_res_blocks: 3
          attn_resolutions: [ ]
          dropout: 0.0

        lossconfig:
          target: torch.nn.Identity

    #cond_stage_config: "__is_first_stage__"

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
      params:
        freeze: True
        layer: "penultimate"

data:
  batch_size: 16
  base_dir: /home/first/data
  json_list: ["jsons/abdomen_ct2mr.json", "jsons/abdomen_mr2ct.json", "jsons/brain_ct2mr.json", "jsons/brain_mr2ct.json", "jsons/brain_cbct2ct.json", "jsons/pelvis_ct2mr.json", "jsons/pelvis_mr2ct.json", "jsons/pelvis_cbct2ct.json"]
  num_workers: 8
  pin_memory: True